version: '3.8'

services:
  portfolio:
    image: node:lts-alpine3.14
    container_name: portfolio
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: yarn dev
    ports:
      - 3000:3000
